<?php

/**
 * @file
 *
 * Integration with Model3D library.
 */

use Drupal\Core\Datetime;
use Drupal\Core\Entity\EntityFormBuilderInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;


/**
 * Implements hook_form_alter().
 */
function lms_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'opigno_statistics_dashboard_form') {
    $skill_table = $form['content_statistics']['skills_list'];
    $training_table = $form['content_statistics']['trainings_list'];
    $skill_table[0]['#header'] = [ t('Data Assesment'), t('Score'), t('Progress') ];
    $form['content_statistics']['skills_list'] = $skill_table;
    $training_table['#header'] = [ t('Training Progocols'), t('# of users'), t('# completed'), t('Ave time spent'), t('Details') ];
    $form['content_statistics']['trainings_list'] = $training_table;
  }
  if($form_id == 'user_register_form') {
    $form['account']['pass']['#process'][] = 'lms_form_user_register_form_process_pass';
  }
}

function lms_form_user_register_form_process_pass(&$element, \Drupal\Core\Form\FormStateInterface $form_state, &$complete_form) {
  $element = \Drupal\Core\Render\Element\PasswordConfirm::processPasswordConfirm($element, $form_state, $complete_form);
  $element['pass1']['#placeholder'] = t('Password');
  $element['pass2']['#placeholder'] = t('Confirm Password');

  return $element;
}


function lms_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if ($entity->getEntityTypeId() == 'node') {
    $type = $entity->get('type')->target_id;

    if ($type == 'page') {
      $user = \Drupal\user\Entity\User::load($account->id());
      $roles = $user->getRoles();
      if (!in_array('administrator', $roles)) {
        return \Drupal\Core\Access\AccessResult::forbidden();
      }
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function lms_entity_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'opigno_notification') {
    /** @var \Drupal\group\Entity\GroupContentInterface $entity */

    if ($entity->isNew()) {
      $message = $entity->get('message')->value;
      $string = $message->getUntranslatedString();
      $argument = $message->getArguments();

      if (strpos($string, "Enrolled to a new training") !== false) {
        $string = str_replace('@name', "\"@name\"", $string);
        $entity->setMessage(t($string, $argument));
      }
    }
  }
}

function lms_js_alter(&$javascript) {
  $javascript['profiles/opigno_lms/modules/opigno/opigno_group_manager/ng/dist/main.bundle.js']['data'] = drupal_get_path('module', 'lms') . '/js/main.bundle.js';
}

function lms_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'training_catalogue')) {
    $view->element['#attached']['library'][] = 'core/drupal.dialog.ajax';
  }
}

function lms_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  if($block->getPluginId() == 'lp_steps_block') {
    $build['#cache']['max-age'] = 0;
  }
}